cp /data/scratch/janani/molevolvr_out/1z6Iw1_*/cln_combined.tsv 1z6Iw1_dnab_dcia_bysp_cln.tsv
cp /data/scratch/janani/molevolvr_out/1z6Iw1_*/ipr_combined.tsv 1z6Iw1_dnab_dcia_bysp_ipr.tsv
cp /data/scratch/janani/molevolvr_out/2aaaq2_*/cln_combined.tsv 2aaaq2_dnab_dcia_bysp_cln.tsv
cp /data/scratch/janani/molevolvr_out/2aaaq2_*/ipr_combined.tsv 2aaaq2_dnab_dcia_bysp_ipr.tsv
cp /data/scratch/janani/molevolvr_out/3emzxS_*/cln_combined.tsv 3emzxS_dnab_dcia_bysp_cln.tsv
cp /data/scratch/janani/molevolvr_out/3emzxS_*/ipr_combined.tsv 3emzxS_dnab_dcia_bysp_ipr.tsv
cp /data/scratch/janani/molevolvr_out/D8wena_*/cln_combined.tsv D8wena_dnab_dcia_bysp_cln.tsv
cp /data/scratch/janani/molevolvr_out/D8wena_*/ipr_combined.tsv D8wena_dnab_dcia_bysp_ipr.tsv
cp /data/scratch/janani/molevolvr_out/DDSVlv_*/cln_combined.tsv DDSVlv_dnab_dcia_bysp_cln.tsv
cp /data/scratch/janani/molevolvr_out/DDSVlv_*/ipr_combined.tsv DDSVlv_dnab_dcia_bysp_ipr.tsv
cp /data/scratch/janani/molevolvr_out/Ex08G6_*/cln_combined.tsv Ex08G6_mtb_dcia_bysp_cln.tsv
cp /data/scratch/janani/molevolvr_out/Ex08G6_*/ipr_combined.tsv Ex08G6_mtb_dcia_bysp_ipr.tsv
cp /data/scratch/janani/molevolvr_out/IM7m65_*/cln_combined.tsv IM7m65_dnab_dcia_bysp_cln.tsv
cp /data/scratch/janani/molevolvr_out/IM7m65_*/ipr_combined.tsv IM7m65_dnab_dcia_bysp_ipr.tsv
cp /data/scratch/janani/molevolvr_out/MPVQrV_*/cln_combined.tsv MPVQrV_dnab_dcia_bysp_cln.tsv
cp /data/scratch/janani/molevolvr_out/MPVQrV_*/ipr_combined.tsv MPVQrV_dnab_dcia_bysp_ipr.tsv
cp /data/scratch/janani/molevolvr_out/NrJ9ML_*/cln_combined.tsv NrJ9ML_dcia21_bydom_cln.tsv
cp /data/scratch/janani/molevolvr_out/NrJ9ML_*/ipr_combined.tsv NrJ9ML_dcia21_bydom_ipr.tsv
cp /data/scratch/janani/molevolvr_out/S82Hpr_*/cln_combined.tsv S82Hpr_dcia73_bydom_cln.tsv
cp /data/scratch/janani/molevolvr_out/Yzxwo1_*/cln_combined.tsv Yzxwo1_dnab_dcia_bysp_cln.tsv
cp /data/scratch/janani/molevolvr_out/Yzxwo1_*/ipr_combined.tsv Yzxwo1_dnab_dcia_bysp_ipr.tsv
cp /data/scratch/janani/molevolvr_out/dDVAZz_*/cln_combined.tsv dDVAZz_dnab_dcia_bysp_cln.tsv
cp /data/scratch/janani/molevolvr_out/dDVAZz_*/ipr_combined.tsv dDVAZz_dnab_dcia_bysp_ipr.tsv
cp /data/scratch/janani/molevolvr_out/eJZq8N_*/cln_combined.tsv eJZq8N_dnab_dcia_bysp_cln.tsv
cp /data/scratch/janani/molevolvr_out/eJZq8N_*/ipr_combined.tsv eJZq8N_dnab_dcia_bysp_ipr.tsv
cp /data/scratch/janani/molevolvr_out/hbDtb5_*/cln_combined.tsv hbDtb5_mtb_dcia_bydom_cln.tsv
cp /data/scratch/janani/molevolvr_out/hbDtb5_*/ipr_combined.tsv hbDtb5_mtb_dcia_bydom_ipr.tsv
cp /data/scratch/janani/molevolvr_out/hzTGBT_*/cln_combined.tsv hzTGBT_dnab_dcia_bysp_cln.tsv
cp /data/scratch/janani/molevolvr_out/hzTGBT_*/ipr_combined.tsv hzTGBT_dnab_dcia_bysp_ipr.tsv
cp /data/scratch/janani/molevolvr_out/lkjyXa_*/cln_combined.tsv lkjyXa_dnab_dcia_bysp_cln.tsv
cp /data/scratch/janani/molevolvr_out/lkjyXa_*/ipr_combined.tsv lkjyXa_dnab_dcia_bysp_ipr.tsv
cp /data/scratch/janani/molevolvr_out/muIlhx_*/cln_combined.tsv muIlhx_dnab_dcia_bysp_cln.tsv
cp /data/scratch/janani/molevolvr_out/muIlhx_*/ipr_combined.tsv muIlhx_dnab_dcia_bysp_ipr.tsv
cp /data/scratch/janani/molevolvr_out/nwWQaX_*/cln_combined.tsv nwWQaX_dnab_dcia_bysp_cln.tsv
cp /data/scratch/janani/molevolvr_out/nwWQaX_*/ipr_combined.tsv nwWQaX_dnab_dcia_bysp_ipr.tsv
cp /data/scratch/janani/molevolvr_out/puXNAe_*/cln_combined.tsv puXNAe_dnab_dcia_bysp_cln.tsv
cp /data/scratch/janani/molevolvr_out/puXNAe_*/ipr_combined.tsv puXNAe_dnab_dcia_bysp_ipr.tsv
cp /data/scratch/janani/molevolvr_out/uLlzqw_*/cln_combined.tsv uLlzqw_dnab_dcia_bysp_cln.tsv
cp /data/scratch/janani/molevolvr_out/uLlzqw_*/ipr_combined.tsv uLlzqw_dnab_dcia_bysp_ipr.tsv
